* SETTINGS                                                         :noexport:
#+STARTUP: indent
#+LATEX_CLASS: article
#+TAGS: export noexport
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+TITLE: 一种基于CFD和深度学习的锅炉温度场预测方法
#+AUTHOR: 
#+DATE: 
#+OPTIONS: toc:nil
##+LATEX_HEADER: \usepackage{tikz}
##+LATEX_HEADER: \tikzset{box/.style={rectangle,minimum width=5cm,minimum height=20pt,inner sep=5pt,draw=black,fill=white},node distance=1.5cm}
* 摘要
（想法是在利用文章的cfd部分之后可以加入深度学习部分）本发明公开了{{{title}}}，
* 权利要求书
1. {{{title}}}，其特征在于可以较快速的预测温度场，包括如下步骤：
   - 步骤一、选用Gambit建立四角切圆锅炉的几何模型并且进行适当的简化；
   - 步骤二、进行网格划分，在不规则区域使用非结构化网格，分区域对网格进行构建；
   - 步骤三、采用CFD设置模型参数，不断迭代直至收敛，通过改变入口的边界条件，得到不同工况下的锅炉的温度场分布数据，从而建立了锅炉的温度场样本数据库；
   - 步骤四、构建预测锅炉温度场的神经网络cGAN
   - 步骤五、训练预测锅炉温度场的神经网络cGAN
   - 步骤六、在训练完成后，得到一个以工况作为输入，温度矩阵作为输出的生成器，再分别将不同平面的工况数据输入所述的生成器，最终得到锅炉温度场。
2. 如权利要求1所述的{{{title}}}，其特征在于：因为过热器对锅炉内部发生的燃烧情况不构成影响，通过简化过热器来达到简化模型的目的。
3. 如权利要求1所述的{{{title}}}，其特征在于：分区域对网格进行构建，在燃烧器区域附加密网格，使计算范围内的网格相对独立，最大程度上降低网格的数量，加快计算速度。网格的数目约为326万。
4. 如权利要求1所述的{{{title}}}，其特征在于：选择k-\varepsilon湍流模型、当涉及对象为气体燃料在辐射炉中燃烧的情况，还要采用与容积化学反应相关的组分输运模型，燃料和空气进口边界条件均为质量流量，出口边界条件为静压，管壁设为壁面边界条件。
5. 如权利要求1所述的{{{title}}}，其特征在于：将cGAN网络的损失函数：\(L=arg min maxV(G,D)+\LambdaL(y,G(x))\)
   其中，V(G,D)=E_x~Pimage [logD(x|y)]+E_Z~P_z (Z)[log(1-D(G(z|y)))]
   \[y=\begin{cases}
     \frac{1}{2}(y-G(x))^{2},\quad if|y-G(x)|\leq \delta \\
     \delta*(|y-G(x)|-frac{1}{2}\delta),\quad otherwise
   \end{cases}\]
   式中，x代表输入的工况，y代表真实温度场，G(·)代表生成器，D(·)代表判别器，\delta为Huber Loss损失函数中自定义的参数，\lambda为自定义的权重值。
* 说明书
{{{title}}}
** 技术领域
本发明是一种锅炉的温度场的预测方法，特别是涉及一种基于CFD和深度学习的锅炉温度场预测方法。
** 背景技术
锅炉作为能源的主要消耗者，具有重要的研究意义。计算流体力学(CFD)在锅炉数值模拟中得到广泛应用，实际情况下，需要大量CFD数据才能得到锅炉温度场分布图，耗时长。而现如今风电、光伏的并网给电力系统稳定性造成了冲击，因此快速预测锅炉温度场分布，有利于调整锅炉运行，实现调频调峰的作用，保证电网稳定运行。

cGAN是GAN(GenerativeAdversarialNets，生成对抗网络)的改进版本。GAN包含生成器和判别器两部分，生成器利用输入的随机噪声生成特定的数据，判别器的作用是判断输入数据的真假，即分辨出输入数据为生成器的输出数据还是真实数据。生成器的优化目标在于生成的数据分布更接近真实数据，使得判别器无法分辨。判别器的优化目标为增强辨别能力，尽可能分辨出生成数据与真实数据。随着网络迭代次数的增加，生成器与判别器相互对抗、竞争，最终得到效果更好的生成器与判别器。cGAN在生成器和判别器的输入中加入了条件变量，对数据的生成进行条件约束，数据的生成更加具有方向性。
** 发明内容
为了解决现在CFD数据量大计算缓慢的问题，本发明提供了{{{title}}}。该方法通过改进的cGAN网络，可以较快速地得到锅炉的温度场的预测值。

本发明所采用的技术方案是：

1. 步骤一
** 附图说明
** 具体实施方式
