* SETTINGS                                                         :noexport:
#+STARTUP: indent
#+LATEX_CLASS: article
#+TAGS: export noexport
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+TITLE: 一种基于CFD和深度学习的锅炉温度场预测方法
#+AUTHOR: 
#+DATE: 
#+OPTIONS: toc:nil
##+LATEX_HEADER: \usepackage{tikz}
##+LATEX_HEADER: \tikzset{box/.style={rectangle,minimum width=5cm,minimum height=20pt,inner sep=5pt,draw=black,fill=white},node distance=1.5cm}
* 摘要
本发明公开了{{{title}}}。本发明首先用Gambit建立四角切圆锅炉的模型并进行适当的简化，然后进行CFD数值模拟得到锅炉的温度场样本数据库，将得到的样本数据对改进的神经网络进行训练，在完成网络训练之后，得到一个以工况作为输入，温度矩阵作为输出的生成器。将不同平面的工况数据输入得到的生成器，最终得到锅炉的预测温度场。本方法在传统的CFD上结合了神经网络，提高了预测的实时性和系统的泛化能力。
* 权利要求书
1. {{{title}}}，其特征在于可以较快速的预测温度场，包括如下步骤：
   - 步骤一、选用Gambit建立四角切圆锅炉的几何模型并且进行适当的简化；
   - 步骤二、进行网格划分，在不规则区域使用非结构化网格，分区域对网格进行构建；
   - 步骤三、采用CFD设置模型参数，不断迭代直至收敛，通过改变入口的边界条件，得到不同工况下的锅炉的温度场分布数据，从而建立了锅炉的温度场样本数据库；
   - 步骤四、构建预测锅炉温度场的神经网络cGAN
   - 步骤五、训练预测锅炉温度场的神经网络cGAN
   - 步骤六、在训练完成后，得到一个以工况作为输入，温度矩阵作为输出的生成器，再分别将不同平面的工况数据输入所述的生成器，最终得到锅炉温度场。
2. 如权利要求1所述的{{{title}}}，其特征在于：因为过热器对锅炉内部发生的燃烧情况不构成影响，通过简化过热器来达到简化模型的目的。
3. 如权利要求1所述的{{{title}}}，其特征在于：对模型进行合适的划分，分区域对网格进行构建。为了尽可能的在规则区域使用结构化网格，以满足模型的精度要求，在保证网格可以在短时间内生成的同时，尽可能地提高网格质量；在不规则区域使用非结构化网格，可以提高计算精度，细化网格，对流场有更好的适应性，依据炉膛的结构特点和烟气的流动特点。在燃烧器区域附近加密网格，使计算范围内的网格相对独立，最大程度上降低网格的数量，加快计算速度。经过数次实验，得到了较好的网格质量。本方法网格质量符合要求，网格数目约为326万。值得说明的是，论文在开始大规模地进行数值模拟之前，对于网格无关性检验进行了研究与分析，并对网格质量进行了检验。本方法通过改变不同大小的网格尺度，研究它们在选取截面上的温度场分布情况。当网格数量增多，但是温度变化并不明显时，为了减少CFD计算时长，节约计算成本，本方法选择网格节点较少的网格尺寸。
4. 如权利要求1所述的{{{title}}}，其特征在于：为了实现有效的数值模拟，选择\(k-\varepsilon\)湍流模型、当涉及对象为气体燃料在辐射炉中燃烧的情况，还要采用与容积化学反应相关的组分输运模型，燃料和空气进口边界条件均为质量流量，出口边界条件为静压，管壁设为壁面边界条件。
5. 如权利要求1所述的{{{title}}}，其特征在于：将cGAN网络的损失函数：\[L=\arg \min_{G} \max_{D}{V}(G,D)+\lambda L(y,G(x))\]
   其中，\(V(G,D)=E_{x\sim Pimage} [log D (x|y)]+E_{Z\sim P_z (z)}[log(1-D(G(z|y)))]\) 
   \[\emph{L}_{\delta}(y,G(x))=\left\{\begin{array}
   \frac{1/}{2}(y-G(x))^{2},\quad &if |y-G(x)|\leq \delta \\
   \delta\cdot\(|y-G(x)|-\frac{1}{2}\delta),\quad &otherwise.
   \end{array}\]
   式中，\(x\)代表输入的工况，\(y\)代表真实温度场，\[G(\cdot)\]代表生成器，\[D(\cdot\))\]代表判别器，\(\delta\)为Huber Loss损失函数中自定义的参数，\(\lambda\)为自定义的权重值。
* 说明书
{{{title}}}
** 技术领域
本发明是一种锅炉的温度场的预测方法，特别是涉及一种基于CFD和深度学习的锅炉温度场预测方法。
** 背景技术
锅炉作为能源的主要消耗者，具有重要的研究意义。计算流体力学(CFD)在锅炉数值模拟中得到广泛应用，实际情况下，需要大量CFD数据才能得到锅炉温度场分布图，耗时长。而现如今风电、光伏的并网给电力系统稳定性造成了冲击，因此快速预测锅炉温度场分布，有利于调整锅炉运行，实现调频调峰的作用，保证电网稳定运行。
计算流体力学(Computational fluid dynamics--CFD)是一门通过数值方法求解流体控制方程组来预测流体的流动、传热、传质、化学反应等相关物理现象的学科。CFD可以计算出十分详尽丰富的锅炉三维温度场数据，但是CFD计算量大，收敛慢，难以获得实时温度场。
cGAN是GAN(GenerativeAdversarialNets，生成对抗网络)的改进版本。GAN包含生成器和判别器两部分，生成器利用输入的随机噪声生成特定的数据，判别器的作用是判断输入数据的真假，即分辨出输入数据为生成器的输出数据还是真实数据。生成器的优化目标在于生成的数据分布更接近真实数据，使得判别器无法分辨。判别器的优化目标为增强辨别能力，尽可能分辨出生成数据与真实数据。随着网络迭代次数的增加，生成器与判别器相互对抗、竞争，最终得到效果更好的生成器与判别器。cGAN在生成器和判别器的输入中加入了条件变量，对数据的生成进行条件约束，数据的生成更加具有方向性。
** 发明内容
为了解决现在CFD数据量大计算缓慢的问题，本发明提供了{{{title}}}。该方法通过改进的cGAN网络，可以较快速地得到锅炉的温度场的预测值。

本发明所采用的技术方案是：

1. 步骤一、选用Gambit建立四角切圆锅炉的几何模型并且进行适当的简化。
   因为过热器对锅炉内部发生的燃烧情况不构成影响，通过简化过热器来达到简化模型的目的。   
2. 步骤二、进行网格划分，在不规则区域使用非结构化网格，分区域对网格进行构建。
   对模型进行合适的划分，分区域对网格进行构建。为了尽可能的在规则区域使用结构化网格，以满足模型的精度要求，在保证网格可以在短时间内生成的同时，尽可能地提高网格质量；在不规则区域使用非结构化网格，可以提高计算精度，细化网格，对流场有更好的适应性，依据炉膛的结构特点和烟气的流动特点。在燃烧器区域附近加密网格，使计算范围内的网格相对独立，最大程度上降低网格的数量，加快计算速度。经过数次实验，得到了较好的网格质量。本方法网格质量符合要求，网格数目约为326万。值得说明的是，论文在开始大规模地进行数值模拟之前，对于网格无关性检验进行了研究与分析，并对网格质量进行了检验。本方法通过改变不同大小的网格尺度，研究它们在选取截面上的温度场分布情况。当网格数量增多，但是温度变化并不明显时，为了减少CFD计算时长，节约计算成本，本方法选择网格节点较少的网格尺寸。
3. 步骤三、采用CFD设置模型参数，不断迭代直至收敛，通过改变入口的边界条件，得到不同工况下的锅炉的温度场分布数据，从而建立了锅炉的温度场样本数据库。
   为了实现有效的数值模拟，选择\(k-\varepsilon\)湍流模型、当涉及对象为气体燃料在辐射炉中燃烧的情况，还要采用与容积化学反应相关的组分输运模型，燃料和空气进口边界条件均为质量流量，出口边界条件为静压，管壁设为壁面边界条件。
4. 步骤四、构建预测锅炉温度场的神经网络cGAN
   将cGAN网络的损失函数：\[\emph{L}=\arg \min_{\emph{G}} \max_{\emph{D}}\emph{V}(\emph{G},\emph{D})+\lambda \emph{L}(y,\emph{G}(x))\]
   其中，\(V(G,D)=E_{x\sim Pimage} [log D (x|y)]+E_{Z\sim P_z (z)}[log(1-D(G(z|y)))]\) 
   \[\emph{L}_{\delta}(y,G(x))=\left\{\begin{array}
   \frac{1/}{2}(y-G(x))^{2},\quad &if |y-G(x)|\leq \delta \\
   \delta\cdot\(|y-G(x)|-\frac{1}{2}\delta),\quad &otherwise.
   \end{array}\]
5. 步骤五、训练预测锅炉温度场的神经网络cGAN
6. 步骤六、在训练完成后，得到一个以工况作为输入，温度矩阵作为输出的生成器，再分别将不同平面的工况数据输入所述的生成器，最终得到锅炉温度场。
本方法在传统的CFD上结合了神经网络，提高了预测的实时性和系统的泛化能力。
** 附图说明
** 具体实施方式

